---
language: python
python:
  - "3.7"
  - "2.7"

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible molecule[docker]

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
