---
language: python
python: "2.7"

sudo: true

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - pip install docker-py
  - ansible --version
  - ansible-galaxy install hxpro.epel

script:
  - ansible-playbook test.yml -i inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
