---
language: python
python:
  - "3.7"
  - "3.6"
  - "2.7"

sudo: true

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - pip install docker-py==1.9.0
  - pip install molecule
  - ansible-galaxy install hxpro.epel
  - ansible-galaxy install hxpro.selinux
  - mv ../ansible-role-phpfpm ../hxpro.phpfpm

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
