---
language: python
python: "2.7"

sudo: true

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version

script:
  - ansible-playbook test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
