---
- name: Check role variables
  assert:
    that:
      - phpfpm_version in phpfpm_supported_versions
      - phpfpm_log_level in phpfpm_allowed_log_levels
      - phpfpm_pools is defined
    msg: "Please read the role documentation, if you still cannot understand why role failed, add your issue."
  tags:
    - setup
    - config

- name: Read version specific variables
  include_vars: "{{ phpfpm_version }}.yml"
  tags:
    - setup
    - config

- name: Install remi-repo
  package: name=https://rpms.remirepo.net/enterprise/remi-release-7.rpm state=installed
  when: ansible_distribution == 'CentOS'
  tags: setup

- name: Install php extensions
  package: name="php{{phpfpm_version}}-php-{{ item }}" state=latest
  with_items: "{{ phpfpm_pkg }}"
  tags: setup

- name: Install other packages
  package: name={{ item }} state=latest
  with_items:
    - gettext
  tags: setup

- name: Home directory for apache user that create php-fpm package
  file:
    name: /usr/share/httpd
    state: directory
  tags: setup

- name: Log directory
  file:
    name: {{ phpfpm_log_path }}
    state: directory
    setype: httpd_log_t
  tags: setup

- sefcontext:
    target: '{{ phpfpm_log_path }}(/.*)?'
    setype: httpd_log_t
    state: present
  when: selinux
  tags: setup

- seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
  when: selinux
  tags: setup

- name: php-fpm.d pool
  include_tasks: "{{ role_path }}/tasks/pool.yml"
  with_items: "{{ phpfpm_pools }}"
  loop_control:
    loop_var: pool
  tags: config

- name: php-fpm.conf
  template: src=php-fpm.conf.j2 dest="{{ phpfpm_etc }}/php-fpm.conf"
    validate="/opt/remi/php{{ phpfpm_version }}/root/usr/sbin/php-fpm -t -c %s"
  notify: restart php-fpm
  tags: config

- name: Customize php.ini
  ini_file:
    path: "{{ phpfpm_etc }}/php.ini"
    section: "{{ item.section | default('PHP') }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ phpfpm_ini }}"
  notify: restart php-fpm
  tags: config

- name: Start/enable php-fpm service
  systemd: name="php{{ phpfpm_version }}-php-fpm" enabled=yes state=started daemon_reload=yes
  tags: setup
