---
- name: Check role variables
  assert:
    that:
      - phpfpm_version in phpfpm_supported_versions
      - phpfpm_log_level in phpfpm_allowed_log_levels
      - phpfpm_pools is defined
    msg: "Please read the role documentation, if you still cannot understand why role failed, add your issue."

- name: Install remi-repo
  package: name=https://rpms.remirepo.net/enterprise/remi-release-7.rpm state=installed
  when: ansible_distribution == 'CentOS'

- name: "Enable remi-php{{ phpfpm_version }}"
  ini_file:
    dest="/etc/yum.repos.d/remi-php{{ phpfpm_version }}.repo"
    section="remi-php{{ phpfpm_version }}"
    option=enabled
    value=1

- name: Install php packages
  package: name={{ phpfpm_pkg }} state=latest

- name: php-fpm.d pool
  include: pool.yml
  with_items: "{{ phpfpm_pools }}"
  loop_control:
    loop_var: pool

- name: php-fpm.conf
  template: src=php-fpm.conf.j2 dest="/etc/php-fpm.conf"
    validate="php-fpm -t -c %s"
  notify: reload php-fpm

- name: Start/enable php-fpm service
  service: name=php-fpm enabled=yes state=started
