---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install deltarpm
      package:
        name: deltarpm
        state: present
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
